package com.sqldexter.organization.entity;
// Generated Mar 26, 2017 5:05:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeductioncodeMaster generated by hbm2java
 */
public class DeductioncodeMaster  implements java.io.Serializable {


     private Integer deductionId;
     private String desription;
     private double deductionAmount;
     private char activeStatus;
     private Date createdDate;
     private Date updatedDate;
     private Integer updatedUserId;
     private char deleteFlag;

    public DeductioncodeMaster() {
    }

	
    public DeductioncodeMaster(String desription, double deductionAmount, char activeStatus, Date createdDate, char deleteFlag) {
        this.desription = desription;
        this.deductionAmount = deductionAmount;
        this.activeStatus = activeStatus;
        this.createdDate = createdDate;
        this.deleteFlag = deleteFlag;
    }
    public DeductioncodeMaster(String desription, double deductionAmount, char activeStatus, Date createdDate, Date updatedDate, Integer updatedUserId, char deleteFlag) {
       this.desription = desription;
       this.deductionAmount = deductionAmount;
       this.activeStatus = activeStatus;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.updatedUserId = updatedUserId;
       this.deleteFlag = deleteFlag;
    }
   
    public Integer getDeductionId() {
        return this.deductionId;
    }
    
    public void setDeductionId(Integer deductionId) {
        this.deductionId = deductionId;
    }
    public String getDesription() {
        return this.desription;
    }
    
    public void setDesription(String desription) {
        this.desription = desription;
    }
    public double getDeductionAmount() {
        return this.deductionAmount;
    }
    
    public void setDeductionAmount(double deductionAmount) {
        this.deductionAmount = deductionAmount;
    }
    public char getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(char activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Integer getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public char getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(char deleteFlag) {
        this.deleteFlag = deleteFlag;
    }




}


