package com.sqldexter.organization.entity;
// Generated Mar 26, 2017 5:05:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MonthlyDeductionTransaction generated by hbm2java
 */
public class MonthlyDeductionTransaction  implements java.io.Serializable {


     private Integer deductionTranId;
     private int deductionId;
     private int employeeId;
     private Date tranDate;
     private double deductionAmount;
     private char activeStatus;
     private Date createdDate;
     private Integer processedUserId;
     private char processFlag;

    public MonthlyDeductionTransaction() {
    }

	
    public MonthlyDeductionTransaction(int deductionId, int employeeId, double deductionAmount, char activeStatus, Date createdDate, char processFlag) {
        this.deductionId = deductionId;
        this.employeeId = employeeId;
        this.deductionAmount = deductionAmount;
        this.activeStatus = activeStatus;
        this.createdDate = createdDate;
        this.processFlag = processFlag;
    }
    public MonthlyDeductionTransaction(int deductionId, int employeeId, Date tranDate, double deductionAmount, char activeStatus, Date createdDate, Integer processedUserId, char processFlag) {
       this.deductionId = deductionId;
       this.employeeId = employeeId;
       this.tranDate = tranDate;
       this.deductionAmount = deductionAmount;
       this.activeStatus = activeStatus;
       this.createdDate = createdDate;
       this.processedUserId = processedUserId;
       this.processFlag = processFlag;
    }
   
    public Integer getDeductionTranId() {
        return this.deductionTranId;
    }
    
    public void setDeductionTranId(Integer deductionTranId) {
        this.deductionTranId = deductionTranId;
    }
    public int getDeductionId() {
        return this.deductionId;
    }
    
    public void setDeductionId(int deductionId) {
        this.deductionId = deductionId;
    }
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Date getTranDate() {
        return this.tranDate;
    }
    
    public void setTranDate(Date tranDate) {
        this.tranDate = tranDate;
    }
    public double getDeductionAmount() {
        return this.deductionAmount;
    }
    
    public void setDeductionAmount(double deductionAmount) {
        this.deductionAmount = deductionAmount;
    }
    public char getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(char activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Integer getProcessedUserId() {
        return this.processedUserId;
    }
    
    public void setProcessedUserId(Integer processedUserId) {
        this.processedUserId = processedUserId;
    }
    public char getProcessFlag() {
        return this.processFlag;
    }
    
    public void setProcessFlag(char processFlag) {
        this.processFlag = processFlag;
    }




}


