package com.sqldexter.organization.entity;
// Generated 18-Mar-2017 13:04:30 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userid;
     private String username;

    public User() {
    }

    public User(String username) {
       this.username = username;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        return "User{" + "userid=" + userid + ", username=" + username + '}';
    }




}


